const defaultProducts=[
{id:1,name:"La Clásica",type:"Hamburguesa",desc:"110 g vacuno · queso · lechuga · tomate · salsa de la casa",price:6500,cost:3500,active:true},
{id:2,name:"La Criolla",type:"Hamburguesa",desc:"110 g vacuno · huevo · cebolla caramelizada · salsa de la casa",price:7500,cost:4100,active:true},
{id:3,name:"Bacon Crunch",type:"Hamburguesa",desc:"110 g vacuno · tocino · cebolla crispy · pepinillo · mermelada de tocino",price:7900,cost:4400,active:true},
{id:4,name:"Doble",type:"Hamburguesa",desc:"220 g vacuno · doble queso · pepinillos · salsa especial",price:8900,cost:5100,active:true},
{id:5,name:"Papas Fritas",type:"Acompañamiento",desc:"Porción de papas fritas",price:3000,cost:1200,active:true},
{id:6,name:"Bebida",type:"Bebestible",desc:"Bebida individual",price:2000,cost:900,active:true}
];

let state={products:[],orders:[],settings:{businessName:"Mi Hamburguesería",businessPhone:"",thanksMessage:"¡Gracias por tu pedido!"}};
let cart=[];

const money=n=>"$"+Math.round(Number(n)||0).toLocaleString("es-CL");
const todayISO=()=>new Date().toISOString().slice(0,10);
const calcMargin=(price,cost)=>price?((price-cost)/price*100):0;
const calcSuggested=(cost,margin)=>{const m=Number(margin)/100;return m>=1?0:Number(cost)/(1-m)};
const escapeHtml=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));

async function persist(){await window.desktopAPI.setData(state)}
async function init(){
  const saved=await window.desktopAPI.getData();
  state=saved||state;
  if(!Array.isArray(state.products)||!state.products.length) state.products=defaultProducts;
  if(!Array.isArray(state.orders)) state.orders=[];
  state.settings={businessName:"Mi Hamburguesería",businessPhone:"",thanksMessage:"¡Gracias por tu pedido!",...(state.settings||{})};
  await persist();
  renderAll();
}

function renderAll(){
  document.getElementById("brandName").textContent=(state.settings.businessName||"Mi Hamburguesería").toUpperCase();
  document.getElementById("businessName").value=state.settings.businessName||"";
  document.getElementById("businessPhone").value=state.settings.businessPhone||"";
  document.getElementById("thanksMessage").value=state.settings.thanksMessage||"";
  renderProducts();renderCart();renderBadges();renderOrders();renderStats();renderAdmin();
}
function goTab(id,btn){["new","orders","cash","admin","settings"].forEach(x=>document.getElementById(x).classList.toggle("hidden",x!==id));document.querySelectorAll(".nav button").forEach(x=>x.classList.remove("active"));btn.classList.add("active");if(id==="orders")renderOrders();if(id==="cash")renderStats();if(id==="admin")renderAdmin()}
function fillCategoryFilter(){const sel=document.getElementById("categoryFilter"),current=sel.value||"all",cats=[...new Set(state.products.map(p=>p.type).filter(Boolean))].sort();sel.innerHTML='<option value="all">Todas las categorías</option>'+cats.map(c=>`<option ${c===current?"selected":""}>${escapeHtml(c)}</option>`).join("")}
function renderProducts(){fillCategoryFilter();const filter=document.getElementById("categoryFilter").value,list=state.products.filter(p=>p.active&&(filter==="all"||p.type===filter));document.getElementById("products").innerHTML=list.length?list.map(p=>`<div class="product"><div class="row between"><span class="status">${escapeHtml(p.type||"Producto")}</span><span class="smalltxt">#${p.id}</span></div><h3>${escapeHtml(p.name)}</h3><div class="muted">${escapeHtml(p.desc||"")}</div><div class="price">${money(p.price)}</div><button class="primary full" onclick="addToCart(${p.id})">+ Agregar</button></div>`).join(""):'<div class="muted">No hay productos disponibles.</div>'}
function addToCart(id){const p=state.products.find(x=>x.id===id);if(!p)return;const c=cart.find(x=>x.id===id);c?c.qty++:cart.push({...p,qty:1});renderCart()}
function changeQty(id,d){const c=cart.find(x=>x.id===id);if(!c)return;c.qty+=d;if(c.qty<=0)cart=cart.filter(x=>x.id!==id);renderCart()}
function cartTotal(){return cart.reduce((s,x)=>s+x.price*x.qty,0)}function cartCost(){return cart.reduce((s,x)=>s+x.cost*x.qty,0)}
function renderCart(){const el=document.getElementById("cart");el.innerHTML=cart.length?cart.map(x=>`<div class="cart-item"><div class="row between"><div><b>${escapeHtml(x.name)}</b><div class="muted">${money(x.price)} c/u</div></div><div class="row"><button class="secondary small" onclick="changeQty(${x.id},-1)">−</button><span class="qty">${x.qty}</span><button class="secondary small" onclick="changeQty(${x.id},1)">+</button></div></div></div>`).join(""):'<div class="muted">Agrega productos desde el menú.</div>';const t=cartTotal(),c=cartCost();document.getElementById("total").textContent=money(t);document.getElementById("cartCost").textContent=money(c);document.getElementById("cartProfit").textContent=money(t-c);document.getElementById("cartMargin").textContent=(t?((t-c)/t*100):0).toFixed(1)+"%"}
function getOrderData(){const t=cartTotal(),c=cartCost();return{id:Date.now(),number:(state.orders.length?Math.max(...state.orders.map(o=>o.number||0)):0)+1,createdAt:new Date().toISOString(),date:new Date().toLocaleString("es-CL"),client:document.getElementById("client").value.trim()||"Sin nombre",phone:document.getElementById("phone").value.trim(),delivery:document.getElementById("delivery").value,payment:document.getElementById("payment").value,address:document.getElementById("address").value.trim(),notes:document.getElementById("notes").value.trim(),items:cart.map(x=>({id:x.id,name:x.name,price:x.price,cost:x.cost,qty:x.qty,type:x.type})),total:t,cost:c,profit:t-c,paid:false,delivered:false,status:"Nuevo"}}
function clearCurrentOrder(){cart=[];renderCart();["client","phone","address","notes"].forEach(id=>document.getElementById(id).value="")}
async function saveOrder(showAlert=true){if(!cart.length){alert("Agrega al menos un producto.");return null}const o=getOrderData();state.orders.unshift(o);await persist();clearCurrentOrder();renderBadges();renderStats();if(showAlert)alert("Pedido #"+o.number+" registrado.");return o}
async function saveAndWhatsApp(){const o=await saveOrder(false);if(!o)return;openWhatsApp(o);alert("Pedido #"+o.number+" registrado y preparado para WhatsApp.")}
function orderMessage(o){return `🍔 *PEDIDO #${o.number}*\nCliente: ${o.client}\n\n${o.items.map(x=>`${x.qty} x ${x.name} — ${money(x.price*x.qty)}`).join("\n")}\n\n*TOTAL: ${money(o.total)}*\nEntrega: ${o.delivery}\nPago: ${o.payment}${o.address?`\nDirección: ${o.address}`:""}${o.notes?`\nObservaciones: ${o.notes}`:""}\n\n${state.settings.thanksMessage||"¡Gracias por tu pedido!"}`}
function openWhatsApp(o){const phone=(o.phone||"").replace(/\D/g,"");const url=phone?`https://wa.me/${phone}?text=${encodeURIComponent(orderMessage(o))}`:`https://wa.me/?text=${encodeURIComponent(orderMessage(o))}`;window.open(url,"_blank")}
async function setOrderStatus(id,val){const o=state.orders.find(x=>x.id===id);if(!o)return;o.status=val;if(val==="Entregado"){o.delivered=true;o.deliveredAt=new Date().toISOString()}await persist();renderOrders();renderBadges();renderStats()}
async function setPaid(id,val){const o=state.orders.find(x=>x.id===id);if(!o)return;o.paid=val==="true";o.paidAt=o.paid?new Date().toISOString():null;await persist();renderOrders();renderBadges();renderStats();if(o.paid)await window.desktopAPI.notify("Pedido pagado",`Pedido #${o.number} · ${o.client} · ${money(o.total)}`)}
async function setDelivered(id,val){const o=state.orders.find(x=>x.id===id);if(!o)return;o.delivered=val==="true";o.deliveredAt=o.delivered?new Date().toISOString():null;if(o.delivered)o.status="Entregado";await persist();renderOrders();renderBadges();renderStats();if(o.delivered)await window.desktopAPI.notify("Pedido entregado",`Pedido #${o.number} · ${o.client}`)}
async function deleteOrder(id){if(!confirm("¿Eliminar este pedido?"))return;state.orders=state.orders.filter(x=>x.id!==id);await persist();renderOrders();renderBadges();renderStats()}
function orderFilterPass(o){const f=document.getElementById("orderFilter")?.value||"all";if(f==="unpaid")return !o.paid;if(f==="undelivered")return !o.delivered;if(f==="today")return(o.createdAt||"").slice(0,10)===todayISO();return true}
function renderOrders(){const list=state.orders.filter(orderFilterPass);document.getElementById("ordersList").innerHTML=list.length?list.map(o=>{const cost=o.cost??o.items.reduce((a,x)=>a+(x.cost||0)*x.qty,0),profit=o.total-cost,margin=calcMargin(o.total,cost);return `<div class="order ${o.paid?"paid":"unpaid"}"><div class="row between wrap"><div><b>#${o.number} · ${escapeHtml(o.client)}</b><div class="smalltxt">${escapeHtml(o.date||"")}</div></div><div class="row wrap"><span class="status ${o.paid?"ok":"bad"}">${o.paid?"PAGADO":"PAGO PENDIENTE"}</span><span class="status ${o.delivered?"ok":"warn"}">${o.delivered?"ENTREGADO":"POR ENTREGAR"}</span></div></div><div class="muted" style="margin:8px 0">${o.items.map(x=>x.qty+"× "+escapeHtml(x.name)).join(" · ")}</div><div class="row between wrap"><b>${money(o.total)}</b><span class="smalltxt">Costo ${money(cost)} · Utilidad ${money(profit)} · Margen ${margin.toFixed(1)}%</span></div><div class="two" style="margin-top:9px"><select onchange="setPaid(${o.id},this.value)"><option value="false" ${!o.paid?"selected":""}>💳 Pago pendiente</option><option value="true" ${o.paid?"selected":""}>💰 Pagado</option></select><select onchange="setDelivered(${o.id},this.value)"><option value="false" ${!o.delivered?"selected":""}>🛵 Entrega pendiente</option><option value="true" ${o.delivered?"selected":""}>✅ Entregado</option></select></div><div class="row wrap" style="margin-top:9px"><select style="flex:1" onchange="setOrderStatus(${o.id},this.value)">${["Nuevo","Confirmado","Preparando","Listo","Entregado"].map(s=>`<option ${s===o.status?"selected":""}>${s}</option>`).join("")}</select><button class="success" onclick="openWhatsAppById(${o.id})">WhatsApp</button><button class="danger" onclick="deleteOrder(${o.id})">Eliminar</button></div></div>`}).join(""):'<div class="muted">No hay pedidos para mostrar.</div>'}
function openWhatsAppById(id){const o=state.orders.find(x=>x.id===id);if(o)openWhatsApp(o)}
function selectedOrdersForStats(){const from=document.getElementById("cashFrom")?.value,to=document.getElementById("cashTo")?.value;return state.orders.filter(o=>{const d=(o.createdAt||"").slice(0,10);if(from&&d<from)return false;if(to&&d>to)return false;return true})}
function renderStats(){const list=selectedOrdersForStats(),sales=list.reduce((s,o)=>s+(o.total||0),0),costs=list.reduce((s,o)=>s+(o.cost??o.items.reduce((a,x)=>a+(x.cost||0)*x.qty,0)),0),profit=sales-costs,collected=list.filter(o=>o.paid).reduce((s,o)=>s+o.total,0),pending=sales-collected;document.getElementById("sales").textContent=money(sales);document.getElementById("costs").textContent=money(costs);document.getElementById("profit").textContent=money(profit);document.getElementById("margin").textContent=(sales?profit/sales*100:0).toFixed(1)+"%";document.getElementById("count").textContent=list.length;document.getElementById("avg").textContent=money(list.length?sales/list.length:0);document.getElementById("collected").textContent=money(collected);document.getElementById("pending").textContent=money(pending)}
function clearCashDates(){document.getElementById("cashFrom").value="";document.getElementById("cashTo").value="";renderStats()}
function renderBadges(){document.getElementById("unpaidBadge").textContent=`💳 ${state.orders.filter(o=>!o.paid).length} por pagar`;document.getElementById("deliveryBadge").textContent=`🛵 ${state.orders.filter(o=>!o.delivered).length} por entregar`}
function renderAdmin(){document.getElementById("adminRows").innerHTML=state.products.map(p=>{const u=p.price-p.cost,m=calcMargin(p.price,p.cost);return `<tr><td><b>${escapeHtml(p.name)}</b><div class="smalltxt">${escapeHtml(p.desc||"")}</div></td><td>${escapeHtml(p.type||"")}</td><td>${money(p.cost)}</td><td>${money(p.price)}</td><td class="green">${money(u)}</td><td>${m.toFixed(1)}%</td><td><span class="status ${p.active?"ok":"bad"}">${p.active?"Disponible":"Oculto"}</span></td><td><div class="row"><button class="blue small" onclick="editProduct(${p.id})">Editar</button><button class="danger small" onclick="deleteProduct(${p.id})">Eliminar</button></div></td></tr>`}).join("")}
function openProductModal(){document.getElementById("modalTitle").textContent="Nuevo producto";document.getElementById("editId").value="";["pName","pType","pDesc","pCost","pPrice"].forEach(id=>document.getElementById(id).value="");document.getElementById("pMargin").value=45;document.getElementById("pActive").value="true";updateSuggestedPrice();document.getElementById("productModal").classList.remove("hidden")}
function closeProductModal(){document.getElementById("productModal").classList.add("hidden")}
function updateSuggestedPrice(){const c=Number(document.getElementById("pCost").value||0),m=Number(document.getElementById("pMargin").value||0);document.getElementById("suggestedPrice").textContent=money(calcSuggested(c,m))}
function editProduct(id){const p=state.products.find(x=>x.id===id);if(!p)return;document.getElementById("modalTitle").textContent="Editar producto";document.getElementById("editId").value=id;document.getElementById("pName").value=p.name;document.getElementById("pType").value=p.type||"";document.getElementById("pDesc").value=p.desc||"";document.getElementById("pCost").value=p.cost;document.getElementById("pPrice").value=p.price;document.getElementById("pActive").value=String(p.active!==false);document.getElementById("pMargin").value=Math.max(1,Math.min(95,Math.round(calcMargin(p.price,p.cost))));updateSuggestedPrice();document.getElementById("productModal").classList.remove("hidden")}
async function saveProduct(){const id=Number(document.getElementById("editId").value||0),name=document.getElementById("pName").value.trim(),type=document.getElementById("pType").value.trim()||"Producto",desc=document.getElementById("pDesc").value.trim(),cost=Number(document.getElementById("pCost").value||0),price=Number(document.getElementById("pPrice").value||0),active=document.getElementById("pActive").value==="true";if(!name){alert("Ingresa el nombre.");return}if(price<=0){alert("Ingresa un precio de venta válido.");return}if(id){Object.assign(state.products.find(x=>x.id===id),{name,type,desc,cost,price,active})}else state.products.push({id:Date.now(),name,type,desc,cost,price,active});await persist();closeProductModal();renderProducts();renderAdmin()}
async function deleteProduct(id){const used=state.orders.some(o=>o.items.some(i=>i.id===id));if(used){if(!confirm("Este producto aparece en pedidos históricos. Se eliminará solo del menú actual. ¿Continuar?"))return}else if(!confirm("¿Eliminar este producto?"))return;state.products=state.products.filter(x=>x.id!==id);await persist();renderProducts();renderAdmin()}
async function saveSettings(){state.settings.businessName=document.getElementById("businessName").value.trim()||"Mi Hamburguesería";state.settings.businessPhone=document.getElementById("businessPhone").value.trim();state.settings.thanksMessage=document.getElementById("thanksMessage").value.trim()||"¡Gracias por tu pedido!";await persist();renderAll();alert("Configuración guardada.")}
async function exportBackup(){const ok=await window.desktopAPI.exportBackup(state);if(ok)alert("Respaldo guardado.")}
async function importBackup(){try{const data=await window.desktopAPI.importBackup();if(!data)return;if(!confirm("Se reemplazarán los datos actuales por el respaldo seleccionado. ¿Continuar?"))return;state=data;await persist();renderAll();alert("Respaldo importado.")}catch(e){alert("No se pudo importar el respaldo.")}}
async function exportOrdersCSV(){const headers=["N°","Fecha","Cliente","Teléfono","Total","Costo","Utilidad","Pagado","Entregado","Estado","Entrega","Pago","Productos"],rows=state.orders.map(o=>[o.number,o.date,o.client,o.phone,o.total,o.cost??0,o.total-(o.cost??0),o.paid?"Sí":"No",o.delivered?"Sí":"No",o.status,o.delivery,o.payment,o.items.map(i=>`${i.qty}x ${i.name}`).join(" | ")]),esc=v=>`"${String(v??"").replace(/"/g,'""')}"`,csv=[headers,...rows].map(r=>r.map(esc).join(";")).join("\n");const ok=await window.desktopAPI.exportCSV(csv);if(ok)alert("CSV exportado.")}

init();
